version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
executors:
  default:
    docker:
     - image: circleci/node:12
    working_directory: ~/project
jobs:
  deploy_backend:
    executor: default
    steps:
      - run: cd backend
workflows:
  heroku_deploy:
    jobs:
      - deploy_backend
      - heroku/deploy-via-git