version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
deployment:
  staging:
    branch: master
    commands:
    - cd/backend
    - git remote add heroku git@heroku.com:servebacksecretapp.git
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
