version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
executors:
  default:
    docker:
     - image: circleci/node:12
    working_directory: ~/backend
workflows:
  heroku_deploy:
    executor: default
    jobs:
      - heroku/deploy-via-git