version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - working_directory: ~/backend
      # - deploy_backend
      - heroku/deploy-via-git