version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
deployment:
  production:
    branch: master
    commands:
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
workflows:
  heroku_deploy:
    jobs:
      - working_directory: ~/backend
      - heroku/deploy-via-git
