version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
jobs:
  deploy:
    executor: heroku/default
    working_directory: ~/backend
    steps:
      - checkout
      - heroku/install
      # - run:
      - heroku/deploy-via-git
workflows:
  heroku_deploy:
    jobs:
      - deploy