version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
jobs:
  deploy_backend:
    steps:
      - checkout
      - run: cd backend
workflows:
  heroku_deploy:
    jobs:
      - deploy_backend
      - heroku/deploy-via-git