version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
executors:
  default:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/backend
jobs:
  deploy_backend:
    executor: default
    steps:
      - attach_project
workflows:
  deploy:
    jobs:
      - deploy_backend
      - deploy-via-git
